/**
 * Background Removal Utility
 * 
 * Removes backgrounds from pet images for clean display
 * Optimized for green screen (#00FF00) backgrounds generated by our AI
 * Uses the built-in image generation service with inpainting/editing
 */

import { generateImage } from "./_core/imageGeneration";

// Green screen color for chroma key removal
const GREEN_SCREEN_COLOR = "#00FF00";

/**
 * Remove background from a pet image
 * Optimized for green screen backgrounds but works with any background
 */
export async function removeBackground(imageUrl: string, isGreenScreen: boolean = true): Promise<{
  success: boolean;
  url?: string;
  error?: string;
}> {
  try {
    // Build prompt based on whether we expect green screen
    const prompt = isGreenScreen
      ? `Remove the solid green background from this image, isolate the creature/pet, make background fully transparent, preserve all creature details and edges, clean chroma key removal`
      : `Isolate the creature/pet in this image, remove the background completely, make background transparent, keep only the main subject, clean edges, no background elements`;
    
    // Use image-to-image with a prompt to isolate the subject
    const result = await generateImage({
      prompt,
      originalImages: [{ url: imageUrl }],
    });
    
    if (!result.url) {
      return {
        success: false,
        error: "Background removal failed"
      };
    }
    
    return {
      success: true,
      url: result.url
    };
  } catch (error) {
    console.error("Background removal error:", error);
    return {
      success: false,
      error: "Background removal failed. Please try again."
    };
  }
}

/**
 * Process a pet image: remove background and optimize for display
 * @param imageUrl - URL of the image to process
 * @param isGreenScreen - Whether the image was generated with green screen background
 */
export async function processPetImage(imageUrl: string, isGreenScreen: boolean = true): Promise<{
  success: boolean;
  processedUrl?: string;
  originalUrl: string;
  error?: string;
}> {
  // First, try to remove the background
  const bgRemovalResult = await removeBackground(imageUrl, isGreenScreen);
  
  if (!bgRemovalResult.success || !bgRemovalResult.url) {
    // If background removal fails, return the original
    return {
      success: true,
      processedUrl: imageUrl,
      originalUrl: imageUrl,
      error: "Background removal unavailable, using original image"
    };
  }
  
  return {
    success: true,
    processedUrl: bgRemovalResult.url,
    originalUrl: imageUrl
  };
}

/**
 * Build a prompt suffix for green screen generation
 * Use this when generating new pet images to ensure easy background removal
 */
export function getGreenScreenPromptSuffix(): string {
  return `, solid bright green background ${GREEN_SCREEN_COLOR}, no shadows on background, clean edges against green`;
}

/**
 * Check if an image likely has a green screen background
 * This is a simple heuristic - in production you'd use actual color analysis
 */
export function isLikelyGreenScreen(imageUrl: string): boolean {
  // For now, assume all AI-generated pet images use green screen
  // In production, you could analyze the image edges or use metadata
  return imageUrl.includes('generated') || imageUrl.includes('pet');
}
